export const GET_COMBAT_CHARS = "GET_COMBAT_CHARS";

export const INITIATIVE_PASS = "INITIATIVE_PASS";

export const SPEED_INCREMENT = "SPEED_INCREMENT";

export const SPEED_DECREMENT = "SPEED_DECREMENT";

export const INIT_INCREMENT1 = "INIT_INCREMENT1";

export const INIT_DECREMENT1 = "INIT_DECREMENT1";

export const INIT_INCREMENT5 = "INIT_INCREMENT5";

export const INIT_DECREMENT5 = "INIT_DECREMENT5";

export const ADD_CHAR = "ADD_CHAR";

export const DEL_CHAR = "DEL_CHAR";

export const CHANGE_ADDCHAR_NAME = "CHANGE_ADDCHAR_NAME";

export const CHANGE_ADDCHAR_SPEED = "CHANGE_ADDCHAR_SPEED";

export const CHANGE_ADDCHAR_SPEEDBONUS = "CHANGE_ADDCHAR_SPEEDBONUS";

export const CHANGE_ADDCHAR_INIT = "CHANGE_ADDCHAR_INIT";

export const AUTH_START = "AUTH_START";

export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const AUTH_FAIL = "AUTH_FAIL";

export const AUTH_CHECK = "AUTH_CHECK";

export const AUTH_SIGNOUT = "AUTH_SIGNOUT";

export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";

export const FETCH_CHARACTERS_FAIL = "FETCH_CHARACTERS_FAIL";

export const FETCH_SHEET_SUCCESS = "FETCH_SHEET_SUCCESS";

export const FETCH_SHEET_FAIL = "FETCH_SHEET_FAIL";
