export const INITIATIVE_PASS = "INITIATIVE_PASS";

export const SPEED_INCREMENT = "SPEED_INCREMENT";

export const SPEED_DECREMENT = "SPEED_DECREMENT";

export const INIT_INCREMENT1 = "INIT_INCREMENT1";

export const INIT_DECREMENT1 = "INIT_DECREMENT1";

export const INIT_INCREMENT5 = "INIT_INCREMENT5";

export const INIT_DECREMENT5 = "INIT_DECREMENT5";

export const ADD_CHAR = "ADD_CHAR";

export const DEL_CHAR = "DEL_CHAR";

export const CHANGE_ADDCHAR_NAME = "CHANGE_ADDCHAR_NAME";

export const CHANGE_ADDCHAR_SPEED = "CHANGE_ADDCHAR_SPEED";

export const CHANGE_ADDCHAR_INIT = "CHANGE_ADDCHAR_INIT";

export const CHANGE_VIEW = "CHANGE_VIEW"

export const CHANGE_EMAIL = "CHANGE_EMAIL"

export const CHANGE_EMAILCONFIRM = "CHANGE_EMAILCONFIRM"

export const CHANGE_USERNAME = "CHANGE_USERNAME"

export const CHANGE_PASSWORD = "CHANGE_PASSWORD"

export const CHANGE_PSWDCONFIRM = "CHANGE_PSWDCONFIRM"

export const ACCEPT_TERMS = "ACCEPT_TERMS"
