export const INITIATIVE_PASS = "INITIATIVE_PASS";

export const SPEED_INCREMENT = "SPEED_INCREMENT";

export const SPEED_DECREMENT = "SPEED_DECREMENT";

export const INIT_INCREMENT5 = "INIT_INCREMENT5";

export const INIT_DECREMENT5 = "INIT_DECREMENT5";

export const INIT_CHANGE = "INIT_CHANGE";

export const ADD_CHAR = "ADD_CHAR";

export const DEL_CHAR = "DEL_CHAR";
